# Site settings
title: Mike Pickfield
tagline: Thoughts and ramblings
description: |
  Mike is a Philosopher who daylights as a software engineer in Toronto, Canada.
  He holds a degree in Physics and Philosophy from the University of Toronto, and ~10 Years of experience in software development.
  He is interested in the intersection of Culture, Economics, and Technology.
email: mike@pickfield.ca
url: https://pickfield.ca
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight # Uncomment and add theme gem to Gemfile when you choose a theme
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
